name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: Build zip
        run: |
         cd purpleair-alexa && zip deployment .env *.py *.json .\env\Lib\site-packages\*
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: purpleair-alexa
          zip_file: purpleair-alexa/deployment.zip